apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
- name: uat
  path: .xlr8s/envs/uat/env.yaml
git:
  repoUrl: git@github.com:XI2999-AChandekar/ameya-project.git
  revision: main
modules:
  k8stools:
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper.git
    ref:
      tag: v0.4.3
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper-constraints.git
    ref:
      tag: v0.1.0
  - module: xebia-istioctl
    ref:
      tag: 1.13.3
  - module: git@github.com:xebiaww-apps/helm-xebia-istio-policies.git
    ref:
      tag: v0.1.1
  - module: git@github.com:xebiaww-apps/helm-xebia-prometheus.git
    ref:
      tag: v0.1.1
  - module: git@github.com:xebiaww-apps/helm-xebia-jaeger.git
    ref:
      tag: v0.2.2
  - module: git@github.com:xebiaww-apps/helm-xebia-kiali.git
    ref:
      tag: v0.4.1
  - module: git@github.com:xebiaww-apps/helm-xebia-metrics-server.git
    ref:
      tag: v0.2.0
  - module: git@github.com:xebiaww-apps/helm-xebia-secrets-store-csi-driver.git
    ref:
      tag: v0.3.0
  - module: git@github.com:xebiaww-apps/helm-xebia-fluent-bit.git
    ref:
      tag: v0.4.3
  - module: git@github.com:xebiaww-apps/helm-xebia-aws-ebs-csi-driver.git
    ref:
      tag: v0.2.0
  - module: git@github.com:xebiaww-apps/helm-xebia-pgadmin.git
    ref:
      tag: v0.1.0
  - module: git@github.com:xebiaww-apps/helm-xebia-prometheus-monitoring-stack.git
    ref:
      tag: v0.3.1
  terraform:
  - module: git@github.com:xebiaww-apps/terraform-aws-xebia-vpc.git
    ref:
      tag: v0.11.0
  - module: git@github.com:xebiaww-apps/terraform-aws-xebia-eks.git
    ref:
      tag: v1.4.0
  - module: git@github.com:xebiaww-apps/terraform-aws-xebia-eks.git
    ref:
      tag: v1.4.2
name: ameya-project-3647
vars:
  apps: null
  policy: null
