apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
git:
  repoUrl: git@github.com:XI2999-AChandekar/ameya-project.git
  revision: main
name: ameya-project-3647
vars:
  apps: null
  policy: null
